# Generated by Django 3.1.7 on 2021-03-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdid', models.IntegerField()),
                ('prdname', models.CharField(max_length=30)),
                ('prdcat', models.CharField(max_length=30)),
                ('prdspec', models.CharField(max_length=30)),
                ('prdprice', models.IntegerField()),
            ],
        ),
    ]
